#!/bin/sh

set -eu

if [ "${GUEST_SESSION:-}" = 'true' ]; then
  exit 0
fi

mode=${1:-}

puavo_domain=$(cat /etc/puavo/domain)
puavo_hosttype=$(cat /etc/puavo/hosttype)

user_primary_group=$(id -gn)

has_device_tag() {
  jq -r .tags[] /etc/puavo/device.json | grep -qx "$1"
}

use_sambahomes() { has_device_tag sambahomes; }

filter_out_our_bookmarks() {
  local bookmarksfile
  local domain_regexp

  bookmarksfile=$1
  domain_regexp=$(echo "${puavo_domain}" | sed 's/\./\\./g')

  # Grep fails if the file is empty or missing, which is ok in this
  # situation: it just means that there is not anything to preserve
  # (or maybe means something else, but probably not serious).
  egrep -v "\.puavo-sharedir|^file:///home/share/|^smb://.*\.${domain_regexp}" \
    "$bookmarksfile" || true
}

update_bookmarks() {
  local bookmarksdir
  local bookmarksfile
  local schooldir_displayname
  local sharename
  local tmpfile
  local userdir_displayname
  local remote_host

  userdir_displayname=$1
  schooldir_displayname=$2
  sharename=$3
  bookmarksfile=$4

  bookmarksdir=$(dirname "${bookmarksfile}")
  mkdir -p "${bookmarksdir}"

  tmpfile="${bookmarksfile}.tmp"

  filter_out_our_bookmarks "${bookmarksfile}" > "${tmpfile}"

  case "$puavo_hosttype" in
    fatclient|ltspserver)
      if use_sambahomes; then
	echo "file://${HOME}/.puavo-sharedir.schooldir/${sharename}/${user_primary_group} ${schooldir_displayname}" >> "${tmpfile}"
      else
	echo "file:///home/share/${sharename}/${user_primary_group} ${schooldir_displayname}" >> "${tmpfile}"
      fi
      ;;
    laptop)
      remote_host=$(dig SRV "_sambaserver._tcp.${puavo_domain}" +short \
          | sed -r -n 's/^[0-9]+ [0-9]+ 139 (.*)\./\1/p' | head -n1)
      if [ -n "${remote_host}" ]; then
          echo "smb://${remote_host}/${USER} ${userdir_displayname}"
          echo "smb://${remote_host}/share/${sharename}/${user_primary_group} ${schooldir_displayname}"
      fi >>"${tmpfile}"
      ;;
  esac

  mv "${tmpfile}" "${bookmarksfile}"
}

case "$(echo $LANG | cut -c 1-2)" in
  fi)
    schooldir_displayname='Yhteiset'
    sharename='yhteiset'
    userdir_displayname='Verkkokansio'
    ;;
  sv)
    schooldir_displayname='Delade filer'
    sharename='delade_filer'
    userdir_displayname='Nätverksmapp'
    ;;
  *)
    schooldir_displayname='Share'
    sharename='share'
    userdir_displayname='Network folder'
    ;;
esac

for bookmark_file in ~/.config/gtk-3.0/bookmarks ~/.gtk-bookmarks; do
  update_bookmarks "$userdir_displayname"   \
                   "$schooldir_displayname" \
                   "$sharename"             \
                   "$bookmark_file"
done


# handle links from user home directory to gvfs-mounts for applications
# that do not understand gvfs

if [ "$mode" = '--with-cleanups' ]; then
  # remove stale links (maybe created later)
  for linkname in 'Yhteiset'     'Delade filer' 'Share' \
                  'Verkkokansio' 'Nätverksmapp' 'Network folder'; do
    [ -h ~/"$linkname" ] && rm -f ~/"$linkname"
  done

  case "$puavo_hosttype" in
    fatclient|ltspserver)
      if ! use_sambahomes; then
        # old stuff, remove
        rmdir ~/.puavo-sharedir.schooldir 2>/dev/null || true
      fi
      ;;
    laptop)
      # old stuff, remove
      rmdir ~/.puavo-sharedir.schooldir \
            ~/.puavo-sharedir.userdir 2>/dev/null || true
      ;;
  esac
fi

case "$puavo_hosttype" in
  fatclient|ltspserver)
    if use_sambahomes; then
      ln -fns ~/.puavo-sharedir.schooldir ~/"${schooldir_displayname}"
    else
      ln -fns "/home/share/${sharename}/${user_primary_group}" \
              ~/"${schooldir_displayname}"
    fi
    ;;
esac
